info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9696
  context-path: /flow
spring:
  application:
    name: v2r1-flow-service
  session:
    store-type: none
jzy:
  aop:
    permission: true