#spring cloud的通用配置
server:
  undertow:
    buffer-size: 1024
  tomcat:
    max-threads: 800 #最大线程数
    min-spare-threads: 100 #最小活跃线程数
    max-connections: 10000 #在任何给定的时间服务器接受并处理的最大连接数
  connection-timeout: 80000 #设置tomcat连接超时时间
info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
spring: 
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker: 
    cache:  false
    request-context-attribute:  request
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  sleuth:
   sampler:
     percentage: 1 #加快收集效率
  cloud:   #启动负载均衡的重试机制，默认false
    loadbalancer:
      retry:
        enabled: true
feign:
  hystrix:
   enabled: true # Feign 整合 Hystrix开启Hystrix断路器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 130000  #设置API网关路由路由转发请求的hystrixCommand执行超时时间 单位毫秒
  threadpool: #线程池核心线程数
    default:
     coreSize: 1000 #缺省为10
ribbon:
  ConnectTimeout: 60000 #请求连接的超时时间
  ReadTimeout: 60000 #请求处理的超时时间
  MaxAutoRetries: 1  #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数
  OkToRetryOnAllOperations: true #对所有操作请求都进行重试
  MaxTotalConnections: 2000   # 默认值
  MaxConnectionsPerHost: 2000 # 默认值
  eager-load: #缓存Ribbon配置
    enabled: true
    clients: v2r1-auth-server,v2r1-platform-service,v2r1-oa-service,v2r1-sys-service,v2r1-disk-service,v2r1-flow-service,v2r1-crm-service,v2r1-attachment-service

####################################  pagerHelper  ########################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
 
privateKey: tje1QgPaUbUWqNY41PKd
LLOA_privateKey: GHOv2pXWBjYAXo13QZNd

#############################权限相关################
jzy:
  baseMappers: # jar包中的mapper
    - com.jzy.hio.sys.test.mapper
  exceptionMap: 
#    500: 系统繁忙,请稍后重试
    0: 至少保留一个key
  aop:
    permission: false
    permissionLoginWhiteList:
      -  /sys/user/queryUserWorkStatus
      -  /sys/redis/
      -  /disk/diskCompanyFile/resetSpace #重置企业网盘空间，暂时使用
    permissionExternalWhiteList: #外部联系人可以访问的白名单
      - /task/queryTaskDetails/  #查询任务详情
    permissionExternalList:  # 外部联系人默认具备的权限
      - /task
      - /disk
      - /flow
      - /project
      - /schedule
    permissionOfflineWhiteList:
      - /sys/organization/queryAllOrganizationsByUserId
      - /sys/organization/update/
      - /sys/app/queryAppByRole
      - /sys/organization/tendInfo/query
    permissionWhiteList: 
      -  /sys/redis/
      -  /comment/
      -  /univ/
      -  /disk/personal  #个人网盘
      -  /disk/attachment  #附件
      -  /disk/thirdParty #第三方文件上传
      -  /flow/instance/flowView   #外部联系人审批
      -  /project/projectInfo/mobile/query #外部联系人调用工程
      -  /project/projectInfo/queryProjectInfoByTeamPerson/ #任务调用项目
      -  /project/projectInfo/queryWhitelistProject  #查询项目详情
      -  /project/projectTeamPerson/queryProjectTeamPersonByProjectId #根据项目id 组装项目团队组织架构树(2.0)
      -  /project/projectTeamPerson/queryProjectTeamPersonByProjectIdBak20180628 #根据项目id 组装项目团队组织架构树(1.0)
      -  /newsType/queryList # 新闻调用栏目
      -  /newsType/get/      # 新闻调用栏目-详情
      -  /contract/contractInfo/get #合同信息
      -  /contract/contractInfo/getContractInfo   #合同查询
      -  /contract/contractPayment/get #合同付款
      -  /contract/contractChange/get #合同变更
      -  /contract/contractChangeType/getContractChangeTypeList #合同变更类型
      -  /contract/contractType/getContractTypeList #合同类型
      -  /contract/contractInfo/getContractGeneratePk #获取合同主键
      -  /contract/contractInfo/getContractInfo #获取合同信息
      -  /contract/contractInfo/saveForApprove #保存合同审批
      -  /contract/contractInfo/delete #删除合同
      -  /contract/contractInfo/updateApproveStatus #更新合同审批状态
      -  /contract/contractChange/getContractChangeForReEdit #重新发起获取合同变更信息
      -  /contract/contractChange/getContractChangeGeneratePk #获取合同变更主键
      -  /contract/contractChange/saveForApprove #保存合同变更审批
      -  /contract/contractChange/delete #删除合同变更
      -  /contract/contractChange/updateApproveStatus #更新合同变更审批状态
      -  /contract/contractPayment/getContractPaymentGeneratePk #获取合同付款主键
      -  /contract/contractPayment/saveForApprove #保存合同付款审批
      -  /contract/contractPayment/delete #删除合同付款
      -  /contract/contractPayment/updateApproveStatus #更新合同付款审批状态
      -  /sys/appUser
      -  /sys/role/saveRole2UserBatch
      -  /sys/user/download/error
      -  /sys/user/download/template
      -  /crm/customer/download/template
      -  /crm/product/download/template
      -  /crm/contact/download/template
      -  /sys/user/delete
      -  /sys/organization/save
      -  /sys/organization/update
      -  /sys/organization/tendInfo/upload
      -  /sys/organization/deleteByIM
      -  /sys/pu
      -  /sys/external
      -  /sys/user/reInviteUserForIM
      -  /sys/organization/queryOrganizationTreeBySelf
    permissionBlackList: 
      - /news/publish  #新闻发布
      - /news/cancel/.*   #新闻取消发布
      - /news/save     #新闻保存
      - /news/delete/.*     #新闻删除
      - /news/top/.*         #新闻置顶
      - /news/top/cancel/.*  #新闻取消置顶
      - /schedule/save      #日程-新增
      - /flow/template/previewTemplate   #预览 
      - /flow/template/draggingSorting   #审批拖拽排序
      - /flow/template/getFlowTemplateById     #基本信息初始化
      - /flow/template/getFlowTemplateParam    #流程配置初始化
      - /flow/templateRole/getFlowTemplateRole  #权限设置初始化
      - /flow/category/getFlowCategoryChildList #分类-流程设计初始化
      - /flow/category/dragCategory      #分类拖拽排序
      - /flow/category/saveFlowCategory     #审批-创建分类
      - /flow/category/deleteFlowCategory  #审批--删除分类
      - /flow/template/saveTemplate        #审批-1.创建审批-模板
      - /flow/template/deleteFlowTemplate  #审批-1.删除审批-模板
      - /flow/customForm/saveCustomForm        #审批-2.表单设计
      - /flow/template/saveFlowTemplateConfigParam     #审批-3.模板配置
      - /flow/templateRole/updateFlowTemplateRole    #审批-4.权限范围
      - /flow/template/enabledDisable                #审批禁用-启用
      - /flow/design/getPage                         #审批查询
      - /crm/productCategory/save       #产品分类新增
      - /crm/productCategory/get/       #产品分类详情查询
      - /crm/productCategory/delete/    #产品分类删除
      - /crm/product/save               #产品新增
      - /crm/product/delete/            #产品删除
      - /crm/product/get/               #产品详情查询
      - /crm/product/page               #产品列表  
      - /crm/product/excel/preview      #导入预览
      - /crm/product/saveImportData     #产品导入
    httpDuplicateSeconds: 1
    httpDuplicateUrl: 
      -  save
      -  update
      -  publish
      -  findPassword
      -  modifyPassword
      -  register