server:
  port: 9092
debug:  true
#logging.level.root=debug
#spring.datasource.druid.url=jdbc:mysql://127.0.0.1:3306/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#spring.datasource.druid.username=root
#spring.datasource.druid.password=root
spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.3.81:3306/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: putest
      password: putest123
      driverClassName:  com.mysql.jdbc.Driver
      initialSize:  1
      minIdle:  1
      maxActive:  200
      maxWait:  60000
      testOnBorrow: true
      testWhileIdle:  false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      timeBetweenEvictionRunsMillis:  300000
      validationQuery:  SELECT 'x'
      maxPoolPreparedStatementPerConnectionSize:  20
      statViewServlet:
        allow:  true

###########################################redis config################################################################

redis:
  host: 192.168.3.21
  port: 6379
  pass: xinleju
  timeout:  100000
  database: 1

############################################jedis#######################################################################
jedis:
  pool:
#    host: 127.0.0.1
#    port: 6379
#    pass:
#    timeout:  100000
#    database: 0
    config:
      maxTotal: 50
      maxIdle:  3
      maxWaitMillis:  100000

############################security config  for swagger start#########################################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin
###############################security config for swagger end##########################################################
jzy:
  swagger-open: true #是否开启swagger (true/false)

