spring:
  application:
    name: hio-sys
  profiles:
    active: dev
  freemarker:
    cache:  false
  freemarker:
    request-context-attribute:  request
# mybatis \u914D\u7F6E
mybatis:
  type-aliases-package: com.jzy.hio.*.*.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
# \u901A\u7528 Mapper \u914D\u7F6E
mapper:
  mappers:  com.jzy.hio.*.*.dao
  not-empty:  false
  identity: MYSQL
###########################################pagehelper###################################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
###########################################eureka#######################################################################
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
#      defaultZone:  http://192.168.3.51:8761/eureka/