info:
  name: "hio-config"
#端口号
server:
  port: 8888
spring:
  application:
    name: hio-config
  profiles:
    active: native

#本地配置地址
  cloud:
    config:
      enabled: true
      server:
       native:
         searchLocations: file:/home/adminuser/test/config/config-core/config/test
  rabbitmq:
    host: 192.168.3.52
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    #服务端地址
    serviceUrl:
      defaultZone:  http://192.168.3.52:8761/eureka/,http://192.168.3.53:8761/eureka/
  instance:
    ip-address: true
logging:
  file: /home/adminuser/test/config/log/hio-config.log
  level:
     root: info