info:
  name: "hio-config"
#端口号
server:
  port: 8888
spring:
  application:
    name: hio-config
  rabbitmq:
    host: 192.168.3.52
    port: 5672
    username: admin
    password: admin
#spring.cloud.config.server.svn.uri    svn配置地址
  cloud:
    config:
      enabled: true
      server:
        svn:
          uri: http://192.168.6.21:1443/svn/erp_cloud_platform/hio-config/src/main/resources/config/
          username: wufei
          password: 12345678
        default-label: test
  profiles:
    active: subversion
eureka:
  client:
    #服务端地址
    serviceUrl:
      defaultZone: http://192.168.3.53:8761/eureka/,http://192.168.3.52:8761/eureka/
  instance:
    ip-address: true # 注册时使用ip而不是主机名
logging:
  file: /home/adminuser/test/config/log/hio-config.log
  level:
     root: info