#项目唯一标示名称
spring:
  applaction:
     name: hio-eureka
  #config-server地址  /{application}-{profile}.properties
#  cloud:
#    config:
#      failFast: true
#      label: master
#      uri: http://localhost:8888
#      profile: dev

#端口号
server:
     port: 8761
#     port: 8762
#配置eureka服务端的信息
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:  # 健康检查
                enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
      renewalThresholdUpdateIntervalMs: 5000

      #服务端地址
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/