#端口号
server:
  port: 8888

info:
  name: "hio-config"
spring:
  application:
    name: hio-config
#spring.cloud.config.server.git.uri    git配置地址
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://gitee.com/goodyluo123/config-repo.git
          lable: master
          search-paths: config-repo/blob
#        svn:
#          uri:
#          username:
#          password:

#    stream:
#      kafka:
#        binder:
#          brokers: 127.0.0.1
#          zkNodes: 127.0.0.1
eureka:
  client:
      #服务端地址
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/