// import Vue from 'vue'
let data={
    "status": {"statusCode": 0, "statusReason": ""},
    "result": {
        "PC":[{
            "id": 10234,
            "groupId": 1,
            "permissionId": 1,
            "resourceName": "巨洲云",
            "resourceDesc": null,
            "belong": null,
            "parentId": null,
            "url": "",
            "tag": null,
            "subject": "PC",
            "type": "部门",
            "status": 1,
            "state": false,
            "isShow":'inside',
            "childFuncs": [{
                "id": 10348,
                "groupId": 1,
                "permissionId": 115,
                "resourceName": "总经办",
                "resourceDesc": null,
                "belong": null,
                "parentId": 114,
                "url": "",
                "tag": null,
                "subject": "PC",
                "type": "按钮",
                "status": 1,
                "state": false,
                "isShow":'inside',
                "childFuncs": [{
                    "id": 103481,
                    "groupId": 1,
                    "permissionId": 1161,
                    "resourceName": "王五",
                    "resourceDesc": null,
                    "belong": null,
                    "parentId": 114,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }]
            }, {
                "id": 10349,
                "groupId": 1,
                "permissionId": 116,
                "resourceName": "综合管理部",
                "resourceDesc": null,
                "belong": null,
                "parentId": 114,
                "url": "",
                "tag": null,
                "subject": "PC",
                "type": "按钮",
                "status": 1,
                "state": false,
                "isShow":'inside',
                "childFuncs": [{
                    "id": 1034912,
                    "groupId": 1,
                    "permissionId": 11622,
                    "resourceName": "李四",
                    "resourceDesc": null,
                    "belong": null,
                    "parentId": 10349,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }]
            }, {
                "id": 10350,
                "groupId": 1,
                "permissionId": 117,
                "resourceName": "赵六",
                "resourceDesc": null,
                "belong": null,
                "parentId": 114,
                "url": "",
                "tag": null,
                "subject": "PC",
                "type": "按钮",
                "status": 1,
                "state": false,
                "isShow":'inside',
                "childFuncs": []
            }, {
                "id": 10351,
                "groupId": 1,
                "permissionId": 118,
                "resourceName": "马奇",
                "resourceDesc": null,
                "belong": null,
                "parentId": 114,
                "url": "",
                "tag": null,
                "subject": "PC",
                "type": "按钮",
                "status": 1,
                "state": false,
                "isShow":'inside',
                "childFuncs": []
            }, {
                "id": 10352,
                "groupId": 1,
                "permissionId": 119,
                "resourceName": "研发中心",
                "resourceDesc": null,
                "belong": null,
                "parentId": 114,
                "url": "",
                "tag": null,
                "subject": "PC",
                "type": "按钮",
                "status": 1,
                "state": false,
                "isShow":'inside',
                "childFuncs": [{
                    "id": 10398,
                    "groupId": 1,
                    "permissionId": 165,
                    "resourceName": "技术部",
                    "resourceDesc": "基础操作功能",
                    "belong": null,
                    "parentId": 164,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }, {
                    "id": 10399,
                    "groupId": 1,
                    "permissionId": 166,
                    "resourceName": "研发一部",
                    "resourceDesc": "基础操作功能",
                    "belong": null,
                    "parentId": 164,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }, {
                    "id": 10400,
                    "groupId": 1,
                    "permissionId": 167,
                    "resourceName": "研发二部",
                    "resourceDesc": "基础操作功能",
                    "belong": null,
                    "parentId": 164,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }, {
                    "id": 10401,
                    "groupId": 1,
                    "permissionId": 168,
                    "resourceName": "测试部",
                    "resourceDesc": "基础操作功能",
                    "belong": null,
                    "parentId": 164,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }, {
                    "id": 10402,
                    "groupId": 1,
                    "permissionId": 169,
                    "resourceName": "待定",
                    "resourceDesc": "日志查看功能",
                    "belong": null,
                    "parentId": 164,
                    "url": "",
                    "tag": null,
                    "subject": "PC",
                    "type": "按钮",
                    "status": 1,
                    "state": false,
                    "isShow":'inside',
                    "childFuncs": []
                }]
            }]
        },{
            "id": 102341,
            "groupId": 11,
            "permissionId": 33311,
            "resourceName": "巨洲云1",
            "resourceDesc": null,
            "belong": null,
            "parentId": -1,
            "url": "",
            "tag": null,
            "subject": "PC",
            "type": "部门1",
            "status": 1,
            "state": false,
            "isShow":'outside',
            "childFuncs": []
        }
    ]}
}

export default data

// if(typeof(Vue)=='undefined'){
//     window.testBigData=data
// }else{
//     module.exports=data
// }
