/**
 * 组件名称不能起名为“ROW”， 它是默认的布局属性
 * 组件内的所有key不允许修改
 * 若须修改请联系开发者：genbin.liu@xyre.com
 */
export default {
  'StdText': {
    wdgName: '文本输入框',
    label: '文本',
    labelDisplay: 'inline',
    isRequired: true,
    isUnique: false,
    dimension: 'md',
    isFlowVar: false,
    valueType: 'str',
    maxLength: 200,
    isHiddenLabel: false,
    defaultValue: '',
    value: '',
    isReadOnly: false,
    placeholder: '请输入内容',
    icon: 'edit',
  },
  'StdTextArea': {
    wdgName: '多行文本框',
    label: '文本',
    labelDisplay: 'inline',
    value: '',
    valueType: 'str',
    defaultValue: '',
    dimension: 'lg',
    maxLength: 200,
    isRequired: false,
    isUnique: false,
    isReadOnly: false,
    isHiddenLabel: false,
    icon: 'edit',
  },
  'StdOptionSelect': {
    wdgName: '下拉列表',
    label: '选择',
    options: [],
    value: '',
    valueType: 'str',
    labelDisplay: 'inline',
    dimension:'lg',
    isFlowVar: false,
    isRequired: false,
    isUnique: false,
    isReadOnly: false,
    isHiddenLabel: false,
    icon: 'edit',
  },
  'StdSingleSelect': {
    wdgName: '单选框',
    label: '单选框',
    options: [],
    value: '',
    valueType: 'str',
    isFlowVar: false,
    isRequired: false,
    isUnique: false,
    labelDisplay: 'inline',
    isHiddenLabel: false,
    isReadOnly: false,
    dimension:'lg',
    maxLength: 20,
    icon: 'edit',
  },
  'StdMultiSelect': {
    wdgName: '复选框',
    label: '复选框',
    options: [],
    value: '',
    valueType: 'str',
    isFlowVar: false,
    isRequired: false,
    isUnique: false,
    labelDisplay: 'inline',
    isReadOnly: false,
    isHiddenLabel: false,
    dimension:'lg',
    icon: 'edit',
  },
  'StdMoney': {
    wdgName: '金额',
    label: '金额',
    labelDisplay: 'inline',
    isRequired: true,
    isUnique: false,
    dimension: 'md',
    isFlowVar: false,
    valueType: 'float',
    maxLength: 20,
    isHiddenLabel: false,
    defaultValue: '',
    value: '',
    isReadOnly: false,
    placeholder: '请输入金额',
    icon: 'edit',
  },
  'StdSingleDate': {
    wdgName: '日期',
    label: '日期',
    labelDisplay: 'inline',
    isRequired: true,
    isUnique: false,
    dimension: 'md',
    isFlowVar: false,
    valueType: 'date',
    maxLength: 20,
    isHiddenLabel: false,
    defaultValue: '',
    value: '',
    isReadOnly: false,
    placeholder: '',
    icon: 'edit',
  },
  'StdIframe': {
    wdgName: '人事表单',
    label: '人事表单',
    labelDisplay: 'block',
    dimension: 'lg',
    linkDataSrc: 'HR',
    link: '/static/hr/hr_jump.html?formMode=instance&bizType=YGZZ&personId=1&businessId=2',
    isHiddenLabel: true,
    icon: 'edit',
  },
  'StdContract': {
    wdgName: '合同表单',
    label: '合同表单',
    labelDisplay: 'block',
    isHiddenLabel: true,
    wdgCallbackType: 'CONTRACT',
    wdgContractType: 'OA_CONTRACT_INFO',
    dimension: 'lg',
    isHiddenLabel: true,
    icon: 'edit',
  },
  // 'StdDepartment': {
  //   wdgName: '部门选择',
  //   label: '部门选择',
  //   labelDisplay: 'inline',
  //   isRequired: true,
  //   isUnique: false,
  //   dimension: 'md',
  //   isFlowVar: false,
  //   valueType: 'str',
  //   maxLength: 200,
  //   isHiddenLabel: false,
  //   defaultValue: '',
  //   value: '',
  //   isReadOnly: false,
  //   placeholder: '请选择部门',
  //   icon: 'edit',
  // },
  // 'StdEmployee': {
  //   wdgName: '人员选择',
  //   label: '人员选择',
  //   labelDisplay: 'inline',
  //   isRequired: true,
  //   isUnique: false,
  //   dimension: 'md',
  //   isFlowVar: false,
  //   valueType: 'str',
  //   maxLength: 200,
  //   isHiddenLabel: false,
  //   defaultValue: '',
  //   value: '',
  //   isReadOnly: false,
  //   placeholder: '请选择人员',
  //   icon: 'edit',
  // },
}


/**
 * 所有属性的对应的样式修改，均在wdg.js中
 * 
 * #: 以#为前缀的组件，只显示在管理员角色中
 * wdgName: 组件名称
 * label：组件左侧的标签名称
 * labelDisplay: 标签显示样式，inline：一行，block：多行
 * valueType: 用户填写的值的类型，传给后端用，int, str, bool, float, date
 * dimension: 组件尺寸，sm，md, lg三种
 * wdgCallbackType: 组件回调类型, ''
 * 
 */
