info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9095
spring:
  application:
    name: v2r1-hr-service
  session:
    store-type: none
  jackson:
#   default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.jzy.hio.hr.*

#本机部署项目路径
deploy:
  path: http://10.17.4.145:8080/platform-app/
endpoint: http://192.168.4.10:7001/WebService/FundExternalService?wsdl


#############################################security config  for swagger ##############################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin
#############################################jzy config  ###############################################################
jzy:
  swagger-open: true #是否开启swagger (true/false)
#断路器默认时间10秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #断路器超时时间
#ribbon超时时间
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    MaxAutoRetries: 1  #重试次数
    MaxAutoRetriesNextServer: 2 #重试服务次数
    OkToRetryOnAllOperations: false #所有请求都开启重试
############################## 
logging:
  file: C:/cloudlog/hrService.log
# level:
#    root: debug
config: classpath:/logback-spring.xml
