spring:
  datasource:
    druid:
    # 192.168.3.81 putest putest123
#      url:  jdbc:mysql://192.168.3.81:3306/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#      username: putest
#      password: putest123
#      url:  jdbc:mysql://192.168.3.149:8066/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      url:  jdbc:mysql://192.168.3.208:8066/hio_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      username: cy1
      password: cy2108cc
#      192.168.3.149 8066 cy1 cy2108cc
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 50
      minIdle: 50
      maxActive: 200
      maxWait:  60000
      testOnBorrow: false
      testWhileIdle: true
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 'x'
      maxPoolPreparedStatementPerConnectionSize: 20
      minEvictableIdleTimeMillis: 300000
      filters: stat,log4j

