jzy:
  aop:
    permission: true
    
#任务创建发送cc消息内容
oa_task_message:  
        save: "发送创建cc消息内容"
        updateStatus: "发送变更cc消息内容"
        update: "发送修改cc消息内容"
        sendMessage: "发送定时cc消息内容"
        
#日程创建发送cc消息内容        
oa_schedule_message: 
            sendMessage: "发送定时cc消息内容"

#定义分布式锁，防止重发操作
redis_key:
    taskOverdue: "hio_oa_task_taskoverdue" #任务超期状态变更
    taskSendMessage: "hio_oa_task_sendMessage" #任务定时发送cc消息
    scheduleMessage: "hio_oa_schedule_sendMessage" #日程定时发送cc消息
    ProjectOverdue: "hio_oa_project_projectoverdue" #项目超期状态变更
    
#项目定时任务执行时间
jobs_schedule:
    ProjectOverdue: "0 1 0 * * ?" #项目超期状态变更执行时间
    
#cc查询详情url
oa_task_details_url: http://192.168.3.157:9999/platform-app/oa/queryTaskDetails 
oa_schedule_details_url: http://192.168.3.157:9999/platform-app/oa/queryScheduleDetails 

#cc查询新闻详情url
newsMobileUrl: "/mobiledist/#/m_details/m_news_detail?id="
newsPcUrl: "/ccdist/#/news/details/"

#cc查询会议详情url
meetingMobileUrl: "/mobiledist/#/m_details/m_meeting_detail?id="
meetingPcUrl: "/ccdist/#/meeting/detail/"
meetingSummaryMobileUrl: "/mobiledist/#/m_meet/meet_summary/"
meetingSummaryPcUrl: "/ccdist/#/meeting/detail/"

# 邮箱服务host
mailbox:
  serverAddress: http://10.17.4.11/jzy_mail/api/fetch-brief.php
