info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 8081
spring:
  application:
    name: hio-admin
  mail: #邮件通知
    host: smtp.126.com
    username: wflovejava@126.com
    password: xxxxxx
  boot:
    admin:
     turbine: #集成turbine
       clusters: HIO-CONSUMER-DEMO,HIO-PROVIDER-DEMO,HIO-API-GATEWAY,SysService	,SearchService,PortalService,FlowService #default 配置要监控的服务
#       url: http://localhost:8992/turbine.stream #指定turbine服务
       location: HIO-TURBINE # turbine 服务名称
    notify: #邮件通知
        mail:
          to: 653367852@qq.com #邮件接收者
          from: wflovejava@126.com #邮件发件人
#          subject: ${application.name}${application.id}${to.status} #邮件主题
#          text: ${application.name} (${application.id})nstatus changed from ${from.status} to ${to.status}\n\n${application.healthUrl} #邮件正文