server:
  port: 9090
  context-path: /sys
spring:
  application:
    name: v2r1-sys-service
# 覆盖springCloud的默认配置    
jzy:
  aop:
    permission: true
  role:
    managerSetup: 你已成功被【{0}】设置为企业管理员！
    # 考勤  培训中心  团队考勤  团队薪资 团队信息  我的信息  我的薪资  
  app:
    externalAppList:   #外部联系人具备的权限
      - 项目 
      - 日程 
      - 云盘
      - 任务 
    imAppList:  # 移动端应用列表
      - 日程  
      - 邮箱
      - 云盘 
      - CRM 
      - 合同
      - 项目
      - 任务
      - 招采
    imAppMap: 
      考勤:
          appId: 1
          name: 考勤  
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 0 # 0 原生
          sort: 2
          state: 1
          mobileUrl: /static/hr/mobile/kq_my_sign.html
          pcUrl: /static/hr/mobile/kq_my_sign.html
      培训中心: 
          appId: 2
          name: 培训中心  
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 8
          state: 1
          mobileUrl: /static/hr/mobile/self/mobile_self_myCourse.html
          pcUrl: /static/hr/mobile/self/mobile_self_myCourse.html
      我的信息:  
          appId: 3
          name: 我的信息  
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 12
          state: 1
          mobileUrl: /static/hr/mobile/self/mobile_self_perInfo.html
          pcUrl: /static/hr/mobile/self/mobile_self_perInfo.html
      我的薪资:  
          appId: 4
          name: 我的薪资 
          moduleId: 1  
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 13
          state: 1
          mobileUrl: /static/hr/mobile/self/mobile_self_salary.html
          pcUrl: /static/hr/mobile/self/mobile_self_salary.html
      团队考勤:  
          appId: 5
          name:  团队考勤  
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 9
          state: 1
          mobileUrl: /static/hr/mobile/self/mobile_self_team_kq.html
          pcUrl: /static/hr/mobile/self/mobile_self_team_kq.html
      团队薪资:  
          appId: 6
          name: 团队薪资 
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 10
          state: 1
          mobileUrl: /static/hr/mobile/self/mobile_self_team_xc.html
          pcUrl: /static/hr/mobile/self/mobile_self_team_xc.html
      团队信息:  
          appId: 7
          name: 团队信息  
          moduleId: 1 
          moduleName: 人事管理
          moduleSort: 1
          type: 1
          sort: 11
          state: 1
          mobileUrl:  /static/hr/mobile/self/mobile_self_team_info.html
          pcUrl:  /static/hr/mobile/self/mobile_self_team_info.html
       