debug:  false
jzy:
  swagger-open: true #是否开启swagger (true/false)
  
spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.3.81:3306/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: putest
      password: putest123
      driverClassName:  com.mysql.jdbc.Driver
      initialSize:  1
      minIdle:  1
      maxActive:  200
      maxWait:  60000
      testOnBorrow: true
      testWhileIdle:  false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      timeBetweenEvictionRunsMillis:  60000
      minEvictableIdleTimeMillis: 300000
      validationQuery:  SELECT 'x'
      maxPoolPreparedStatementPerConnectionSize:  20
#      statViewServlet:
#        allow:  true

 
########################################### jedis config ####################################################
jedis:
  pool:
    host: 127.0.0.1
    port: 6379
    pass:
#    host: 192.168.3.21
#    port: 6379
#    pass: xinleju
    timeout:  100000
    database: 0
    config:
      maxTotal: 50
      maxIdle:  3
      maxWaitMillis:  100000

