spring:
  application:
    name: hio-portal
  profiles:
    active: dev
  freemarker:
    cache:  false
    request-context-attribute:  request

####################################  mybatis  ########################################################
mybatis:
  type-aliases-package: com.jzy.hio.oa.bbs.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
base:
  mapper:
    mappers:  com.jzy.hio.base.mapper
mapper:
  not-empty:  false
  identity: MYSQL
####################################  pagerHelper  ########################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#####################################  eureka  ############################################################
server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.51:8761/eureka/
#      defaultZone:  http://localhost:8761/eureka/

############################ security config  for swagger ##############################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin
