#默认注册中心配置文件
info:
  version: "v2"
  name: "hio"
#端口号
server:
   port: 1111
   tomcat:
     max-threads: 200
spring:
  application:
    name: hio-eureka
eureka:
  instance:
    hostname: 172.17.81.58
    prefer-ip-address: true
  client:
    register-with-eureka: true # false 代表不想在注册中心注册自己
    serviceUrl:
      defaultZone: http://172.17.81.63:1111/eureka/