info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9098
  context-path: /disk
  tomcat:
    max-threads: 200
spring:
  application:
    name: v2r1-disk-service
  data:
    elasticsearch: #ES集群配置
      cluster-name: es-cluster #es集群名
      cluster-nodes: 172.17.81.43,172.17.81.46,172.17.81.51 #ES 集群节点列表
####################################  custom param  ########################################################
disk:
  ifOpenHdfsToRedis: false
  chunkRedisLockSleepTime: 100 #ms
  size: 
    companySpaceSize: 214748364800 #企业网盘空间大小默认200G 214748364800
    personalSpaceSize: 2147483648  #个人网盘空间大小默认2G 2147483648
jzy:
  aop:
    permission: true

hadoop:
  hdfs-url: hdfs://ns
  hdfs-user: hadoop
  hdfs-append: true
  hdfs-root-path:
  hdfsPool: # hdfs 连接池配置
    maxTotal: 16
    maxIdle: 16
    minIdle: 0
    maxWaitMillis: 30000 #如果这个值小于0，则永不超时; 如果大于0，则等待maxWaitMillis长时间,单位是毫秒
file:
  converter:
    path: /mnt/previewArea #文件转换时存放文件的路径 D:\previewArea #
  previewArea:
    ip: http://172.17.81.65 #/FDFS 对应外网访问地址
    regulation-link: http://cc.juzhouyun.com/static/fix-iframe-bugs.js #web端限制excel预览产生的html文件中超链接跳转
downLoad:
  zipPath: /mnt/zipPath/ #打包下载临时保存文件地址  
attachment:
  file:
    temp:
      path: /mnt/attachment/temp/ #保存临时文件地址
    max-size-to-bit: 104857600 #文件最大Bit（100MB）
    
#过滤器配置#     
urlFilter:
     #不过滤列表#
     unfilteredList:
        -  /disk/diskCompanyInit/queryCompanyDiskSpace   