mybatis:
  type-aliases-package: com.jzy.hio.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
  
noticephoneserver:
  idnumber: 127116
  username: Admin
  password: Iu199491

running: 
  standardSteps: 7000 #运动达标步数
  rankingTop: 10 #排行榜前几名
  rankingAll: 100 #排行榜显示人数

queue:
  ImNoticeMsgQueue: im_notice_msg_queue
  ImNoticeMsgTempQueue: im_notice_msg_temp_queue
  imFriendInfoQueue: im_friend_info_queue
  imUserInfoQueue: im_user_info_queue
  shortNoticeMsgQueue: shortNoticeMsgQueue
  imSentimentInfoQueue: im_sentiment_info_queue
  imPersonalSecretQueue: im_personal_secret_queue
  imStarInfoQueue: im_star_info_queue
  imFriendAliasQueue: im_friend_alias_queue
  tenantCompanyInfo: tenant_company_info_queue

huanxin:
  isSendMsg: true   #是否调用环信接口开关
  isSendShortMsg: true  #是否发短信开关
  hioccDownUrl: "https://fir.im/l3aw"  # hiocc 下载地址

#头像上传oss配置
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAIn4HmurfO3XVx
  accessKeySecret: jUMPLLPni0G8mhIuncY6UrENg3eFsp
  ossGroupAvatarBucket: hio-cc-test #群组头像空间
  ossRunningCoverBucket: hio-cc-running #运动封面空间
  domain: http://hio-cc-test.oss-cn-beijing.aliyuncs.com #访问域名
  runningDomain: http://hio-cc-running.oss-cn-beijing.aliyuncs.com #运动封面访问域名
#
#myoauth2:
#  loginUrl: http://192.168.3.157:9999/platform-app/myoauth2/oauth/token
#  scope: hio
#  clientId: hio_oauth
#  clientSecret: hio_secret
#创建团队接口
tendUser:
  adminPhone: 18611425106
#oss:
#  endpoint: http://oss-cn-beijing.aliyuncs.com
#  accessKeyId: LTAIz1my6dUYKVdj
#  accessKeySecret: un0cwkv0WfRkVQtwjD3ERASdzEsKut

#security:
# oauth2:
#  resource:
#   id:
#   user-info-uri: http://localhost:9999/platform-app/uaa2/user
#   prefer-token-info: false

#定义分布式锁，防止重发操作
redis_key:
    ImNoticeMsgTemp: "hio_platform_notice_msg" #重发消息
    ImNoticeMsgPhone: "hio_platform_notice_msg_phone" #删除过期短信
    UserLoginStatus: "hio_platform_user_login" #用户在线状态
from: test1333

system:
    pcVersion: "1.0.0.1"  #pc版本号
    pcUpgradeModel: 1     #升级模式 0：已是最新版本；1：选择是否升级；2：后台自动升级；3：强制升级
    pcUpgradeGrayscale: 1   #灰度
    pcUpgradeScope: ""    # 升级范围，单位：tendId
    pcUpgradeUrl: "http://hio.oss-cn-beijing.aliyuncs.com/juzhouyuncc"    #下载地址