security:
   oauth2:
    resource:
      id:
      user-info-uri: http://59.110.146.137:9999/platform-app/myoauth2/user
      prefer-token-info: false
feign:
  hystirx:
    enable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000  #设置API网关路由路由转发请求的hystrixCommand执行超时时间 单位毫秒
myoauth2:
   loginUrl: http://59.110.146.137:9999/platform-app/myoauth2/oauth/token
   scope: hio
   clientId: hio_oauth
   clientSecret: hio_secret
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
