eureka:
  client:
    service-url:
      defaultZone:  http://localhost:1111/eureka/
  instance:
   lease-expiration-duration-in-seconds: 30
   lease-renewal-interval-in-seconds: 10 #表示eureka client发送心跳给server端的频率 默认30秒
   prefer-ip-address: true #显示服务器IP