info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9091
spring:
  application:
    name: PortalService
  freemarker:
    cache:  false
    request-context-attribute:  request
  jackson:
  # default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
feign:
  hystrix:
   enabled: false
#断路器默认时间10秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #断路器超时时间
#ribbon超时时间
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    MaxAutoRetries: 1  #重试次数
    MaxAutoRetriesNextServer: 2 #重试服务次数
    OkToRetryOnAllOperations: false #所有请求都开启重试
####################################  mybatis  ########################################################
mybatis:
  type-aliases-package: com.jzy.hio.oa.bbs.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
base:
  mapper:
    mappers:  com.jzy.hio.base.mapper
mapper:
  mappers:
    - com.jzy.hio.base.dao.BaseMapper
  not-empty:  false
  identity: MYSQL
####################################  pagerHelper  ########################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

############################ security config  for swagger ##############################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin

privateKey: tje1QgPaUbUWqNY41PKd
LLOA_privateKey: GHOv2pXWBjYAXo13QZNd
jzy:
  swagger-open: false #是否开启swagger (true/false)
##############################
logging:
  file: C:/cloudlog/flowService.log
# level:
#    root: debug
config: classpath:/logback-spring.xml