info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9090
spring:
  application:
    name: FlowService
  session:
    store-type: none
  jackson:
#   default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
base:
  mapper:
    mappers: com.jzy.hio.base.mapper
    
mapper: 
  mappers:
    - com.jzy.hio.base.dao.BaseMapper
  not-empty: false
  identity: MYSQL

mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jzy.hio.flow.entity


#MaChangxi
imServer:
  sendMessage: http://192.168.3.61:80/xyre-mobile/message/send
#  sendMessage: http://im.xyre.com/xyre-mobile/message/send

############  \u5FAE\u4FE1\u914D\u7F6E  ##############
weinxin: 
#\u4F60\u7684\u4F01\u4E1A\u53F7ID
  corpId: wx83edbe88c27100fe
#\u7BA1\u7406\u7EC4\u7684\u51ED\u8BC1\u5BC6\u94A5\uFF0C\u6BCF\u4E2Asecret\u4EE3\u8868\u4E86\u5BF9\u5E94\u7528\u3001\u901A\u8BAF\u5F55\u3001\u63A5\u53E3\u7684\u4E0D\u540C\u6743\u9650\uFF1B\u4E0D\u540C\u7684\u7BA1\u7406\u7EC4\u62E5\u6709\u4E0D\u540C\u7684secret
  corpsecret: Ai5g-OMJYa-HT5rsvL7xy6hULfcOfFrjVB94k6G_r7JQ6a2UuXL84pIpt5fC2udm
  mobiletodo: 
    agentid: 11 #物业审批
#    agentid: 3 #erp微审批

#mobileToDoServer: http://xinleju.ngrok.natapp.cn/mobiletodo
#mobileToDoServerWeiXin:　http://xinleju.ngrok.natapp.cn/mobiletodo
#mobileToDoServer: http://894234ec.ngrok.io/mobiletodo
mobileToDoServer: http://10.17.3.86/platform-app/

mobileToDoServerWeiXin: http://894234ec.ngrok.io/mobiletodo

innerLoginUrl: http://127.0.0.1:8080/platform-app/sys/thirdPartyAuthentication/innerLogin


#本机部署项目路径
deploy:
  path: http://10.17.4.145:8080/platform-app/
endpoint: http://192.168.4.10:7001/WebService/FundExternalService?wsdl

scan:
  approvers: 张勇,张立洲,张爰(Helen),苏海云,王五111
  reciever:
    phones: 18500972036
    cc: zhangdaoqiang

#############################################security config  for swagger ##############################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin
#############################################jzy config  ###############################################################
jzy:
  swagger-open: true #是否开启swagger (true/false)
#断路器默认时间10秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #断路器超时时间
#ribbon超时时间
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    MaxAutoRetries: 1  #重试次数
    MaxAutoRetriesNextServer: 2 #重试服务次数
    OkToRetryOnAllOperations: false #所有请求都开启重试
############################## 
logging:
  file: C:/cloudlog/flowService.log
# level:
#    root: debug
config: classpath:/logback-spring.xml
