info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9411
spring:
  application:
    name: hio-sleuth
  sleuth:
    enabled: false #表示当前程序不使用sleuth
    sampler:
      percentage: 1
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200 #192.168.3.54:9200
#logging:
#  file: C:\cloudlog\hio-sleuth.log
#  level:
#     root: debug
#     org.springframework.cloud.sleuth: DEBUG #为了能在各个微服务的控制台中看到Sleuth的输出，每个微服务配置日志级别，在application.yml中加入以下配置：
#     ZIPKIN_LOG_LEVEL: DEBUG