spring:
  datasource:
    druid:
      url:  jdbc:mysql://192.168.3.81:3306/erp_platform_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: putest
      password: putest123
      driverClassName:  com.mysql.jdbc.Driver
      initialSize:  1
      minIdle:  1
      maxActive:  200
      maxWait:  60000
      testOnBorrow: true
      testWhileIdle:  false
      testOnReturn: false
      removeAbandoned: true
      removeAbandonedTimeout: 60
      timeBetweenEvictionRunsMillis:  300000
      validationQuery:  SELECT 'x'
      maxPoolPreparedStatementPerConnectionSize:  20