#默认注册中心配置文件
info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
#端口号
server:
   port: 1111
   tomcat:
     max-threads: 200
spring:
  application:
    name: hio-eureka
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 11
    prefer-ip-address: true
  client:
    register-with-eureka: true # false 代表不想在注册中心注册自己
    registryFetchIntervalSeconds: 7 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  
logging:
  file: C:\cloudlog\hioEureka.log
#  level:
#    root: info
config: classpath:/logback-spring.xml