spring:
  redis:
    host: 192.168.3.52 #192.168.3.52 localhost
    port: 6379  
    password: xinleju
    database: 1  
    timeout: 10000  
    pool:
      max_total: 50  
      maxWaitMillis: -1
      max_idle: 20
      min_idle: 0