info:
  version: "v2"
  name: "hio"
management:
 security:
  enabled: false #不认证，解决关于springboot-actuator监控的401无权限访问
server:
  port: 9092
spring:
  application:
    name: SysService
  freemarker:
    cache:  false
    request-context-attribute:  request
  jackson:
#    default-property-inclusion: non_null  #null值不能过滤，前端会用到
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
  sleuth:
    sampler:
      percentage: 1.0 #加快收集效率
#断路器默认时间10秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #断路器超时时间
#ribbon超时时间
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
    MaxAutoRetries: 1  #重试次数
    MaxAutoRetriesNextServer: 2 #重试服务次数
    OkToRetryOnAllOperations: false #所有请求都开启重试
# mybatis 配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.jzy.hio.**.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
#
base:
  mapper:
    mappers:  com.jzy.hio.base.mapper
mapper:
  mappers:
    - com.jzy.hio.base.dao.BaseMapper
  not-empty:  false
  identity: MYSQL
###########################################pagehelper###################################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
###########################################eureka#######################################################################
############################security config  for swagger start#########################################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin
###############################security config for swagger end##########################################################
jzy:
  swagger-open: true #是否开启swagger (true/false)
  deploy.path: ""
  endpoint: ""
##############################
attachment:
  port: 8080
##############################
logging:
  file: C:/cloudlog/hioSysService.log
# level:
#    root: debug
config: classpath:/logback-spring.xml
