INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-001', 'TY', '同  意', '同意222', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-27 18:01:48', NULL, NULL, '2017-2-27 10:05:38', 117, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-002', 'ZB', '转办', '转办111', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:17', NULL, NULL, '2017-2-27 11:01:23', 28, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-003', 'DH', '打回', '打回', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:19', NULL, NULL, '2017-2-27 10:13:21', 23, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-004', 'XB', '协办', '协办', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:20', NULL, NULL, '2017-2-27 20:08:45', 20, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-005', 'HF', '回复', '回复', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:21', NULL, NULL, '2017-2-27 14:19:09', 15, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-006', 'GTFQR', '沟通发起人', '沟通发起人', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:22', NULL, NULL, '2017-2-27 11:00:01', 14, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-007', 'WYY', '无异议', '无异议', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:22', NULL, NULL, '2017-2-27 20:24:47', 6, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-008', 'JS', '接受', '接受', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:24', NULL, NULL, '2017-3-17 15:16:48', 4, '0');
INSERT INTO `pt_flow_operation_type` (`id`, `code`, `name`, `remark`, `tend_id`, `create_person_id`, `create_person_name`, `create_org_id`, `create_org_name`, `create_company_id`, `create_company_name`, `create_date`, `update_person_id`, `update_person_name`, `update_date`, `concurrency_version`, `delflag`) VALUES ('basic-operation-type-009', 'BJS', '不接受', '不接受', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2017-2-25 12:28:35', NULL, NULL, '2017-2-27 10:53:31', 10, '0');
