info:
  version: "v2"
  name: "hio"
spring: 
  freemarker: 
    cache:  false
    request-context-attribute:  request
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
feign:
  hystrix:
   enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  #设置API网关路由路由转发请求的hystrixCommand执行超时时间 单位毫秒

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

####################################  pagerHelper  ########################################################
pagehelper:
  helperDialect:  mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

############################ security config  for swagger ##############################################
security:
  basic:
    path: /swagger-ui.html
    enabled:  true
  user:
    name: admin
    password: admin

privateKey: tje1QgPaUbUWqNY41PKd
LLOA_privateKey: GHOv2pXWBjYAXo13QZNd
jzy:
  swagger-open: false #是否开启swagger (true/false)
##############################
logging:
  file: C:/cloudlog/flowService.log
# level:
#    root: debug
config: classpath:/logback-spring.xml