#测试环境配置文件
info:
  name: "hio-config"
#端口号
server:
  port: 8888
spring:
  application:
    name: hio-config
  profiles:
    active: native
  rabbitmq:
    host: 192.168.3.212
    port: 5672
    username: admin
    password: admin
#    virtual-host: /platform

#本地配置地址
  cloud:
    config:
      enabled: true
      server:
       native:
         searchLocations: file:/root/config/stable1/
eureka:
  client:
    #服务端地址
    serviceUrl:
      defaultZone:  http://192.168.3.232:1111/eureka/
  instance:
    ip-address: true