info:
  version: "v2"
  name: "hio"
#端口号
server:
  port: 8888
spring:
  application:
    name: hio-config
  profiles:
    active: native

#本地配置地址
  cloud:
    config:
      enabled: true
      server:
       native:
         search-locations: classpath:/config/test
  # 用途 动态刷新自定义配置
#  rabbitmq:
#    host: 192.168.3.52
#    port: 5672
#    username: admin
#    password: admin
eureka:
  client:
    #服务端地址
    serviceUrl:
      defaultZone:  http://192.168.3.173:1111/eureka/,http://192.168.3.174:1111/eureka/
  instance:
    ip-address: true