#生产环境配置文件
info:
  name: "hio-config"
#端口号
server:
  port: 8888
spring:
  application:
    name: hio-config
  profiles:
    active: native
  rabbitmq:
    host: 172.17.81.41
    port: 5672
    username: platform
    password: platform
    #virtual-host: /platform

#本地配置地址
  cloud:
    config:
      enabled: true
      server:
       native:
         searchLocations: file:/hiov2/config/prod
eureka:
  client:
    #服务端地址
    serviceUrl:
      defaultZone:  http://172.17.81.58:1111/eureka/,http://172.17.81.63:1111/eureka/
  instance:
    ip-address: true