##Tomcat配置
server:
  servlet:
    context-path: /fileServer
  tomcat:
    max-http-post-size: 0
  domain: http://192.168.3.179:8080
  
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.179:3306/jzy_fileserver?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://localhost:3306/jzy_fileserver?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

## 上传文件限制
  servlet:
      multipart:
        maxFileSize: 500MB
        maxRequestSize: 1000MB    

## Mybatis 配置
mybatis:
  typeAliasesPackage: com.jzy.fileserver.domain
  mapperLocations: classpath:mapper/*.xml

## 打印机配置
printer:
  address: 
    - id: 1
      host: 192.168.3.179
      servicePort: 9090
      eventPort: 9930

#    - id: 2
#      host: 192.168.3.178
#      servicePort: 9090
#      eventPort: 9930
  timeout: 60 #seconds
  headerLength: 2

## 文件存储
file:
  location: D:\test
  
print.retry.time: 60000 #1minutes

broadcast:
  host: 192.168.3.189
  port: 9091
