#默认注册中心配置文件
info:
  version: "开发版本20180112"
  name: "hio"
#端口号
server:
   port: 1111
   tomcat:
     max-threads: 200
spring:
  application:
    name: hio-eureka
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 11
    prefer-ip-address: true
  client:
    register-with-eureka: true # false 代表不想在注册中心注册自己
    registryFetchIntervalSeconds: 7 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
 # server:
#  自我保护模式
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 20000
logging:
  file: C:/cloudlog/hioEureka.log
  level:
    root: INFO