spring:
#    redis单节点配置
  redis:
    host: 192.168.3.52 #192.168.3.52 localhost
    port: 6379  
    password: xinleju
    database: 1  
    timeout: 10000  
    pool:
      max_total: 50  
      maxWaitMillis: -1
      max_idle: 20
      min_idle: 0
redis:
   cluster:
    nodes: 192.168.3.55:6379,192.168.3.55:6380,192.168.3.55:6381,192.168.3.55:6382,192.168.3.55:6383,192.168.3.55:6384
    database: 0
    connectionTimeout: 60000 #
    soTimeout: 1000 #
    password: xinleju
    pool:
      maxTotal: 8 #最大连接数
      maxIdle: 6 #闲置最大连接数
      minIdle: 0 #闲置最小连接数
      maxWaitMillis: 15000 # 到达最大连接数后，调用者阻塞时间
      minEvictableIdleTimeMillis: 300000 #连接空闲的最小时间，可能被移除
      softMinEvictableIdleTimeMillis: -1 #连接空闲的最小时间，多余最小闲置连接的将被移除
      numTestsPerEvictionRun: 3 #设置每次检查闲置的个数
      testOnBorrow: false #申请连接时，是否检查连接有效
      testOnReturn: false #返回连接时，是否检查连接有效
      testWhileIdle: false #空闲超时,是否执行检查有效
      timeBetweenEvictionRunsMillis: 60000 #空闲检查时间
      blockWhenExhausted: true #当连接数耗尽，是否阻塞
disk:
  redis:
    host: 192.168.3.170 #192.168.3.170 localhost
    port: 6379
    password: xinleju
    database: 1
    timeout: 15000
    pool:
      maxTotal: 50 #最大连接数
      maxIdle: 6 #闲置最大连接数
      minIdle: 0 #闲置最小连接数
      maxWaitMillis: 15000 #到达最大连接数后，调用者阻塞时间
      minEvictableIdleTimeMillis: 300000 #连接空闲的最小时间，可能被移除
      softMinEvictableIdleTimeMillis: -1 #连接空闲的最小时间，多余最小闲置连接的将被移除
      numTestsPerEvictionRun: 3 #设置每次检查闲置的个数
      testOnBorrow: false #申请连接时，是否检查连接有效
      testOnReturn: false #返回连接时，是否检查连接有效
      testWhileIdle: false #空闲超时,是否执行检查有效
      timeBetweenEvictionRunsMillis: 60000 #空闲检查时间
      blockWhenExhausted: true #当连接数耗尽，是否阻塞
      
   