security:
   oauth2:
    resource:
      id:
      user-info-uri: http://localhost:9998/user
      prefer-token-info: false
feign:
  hystirx:
    enable: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000  #设置API网关路由路由转发请求的hystrixCommand执行超时时间 单位毫秒
myoauth2:
   loginUrl: http://localhost:9998/oauth/token
   scope: hio
   clientId: hio_oauth
   clientSecret: hio_secret
